FROM nginx:alpine

# Copy pre-built files
COPY client/build /usr/share/nginx/html

# Copy nginx configuration
COPY k8s/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
