const Product = require('../models/Product');
const PurchaseOrder = require('../models/PurchaseOrder');
const Supplier = require('../models/Supplier');
const OrderCounter = require('../models/OrderCounter');

/**
 * Reorder System — auto-generates draft purchase orders for low-stock products.
 * Uses Economic Order Quantity (EOQ) for optimal order quantity.
 * Groups items by supplier for consolidated POs.
 */
class ReorderSystem {
  /**
   * Reorder point: average daily demand × lead time + safety stock
   */
  static calculateReorderPoint(product, leadTimeDays = 7) {
    const dailyDemand = (product.salesCount || 0) / 30;
    const safetyStock = dailyDemand * 3;
    return Math.max(Math.ceil((dailyDemand * leadTimeDays) + safetyStock), product.lowStockThreshold || 10);
  }

  /**
   * Economic Order Quantity formula
   * EOQ = sqrt(2 × D × S / H)
   * D = annual demand, S = order cost, H = holding cost per unit
   */
  static calculateEOQ(annualDemand, orderCost = 150, holdingCostPerUnit = 20) {
    if (annualDemand <= 0) return 10;
    return Math.max(Math.ceil(Math.sqrt((2 * annualDemand * orderCost) / holdingCostPerUnit)), 1);
  }

  /**
   * Check all products and auto-generate draft POs for those below reorder point.
   * Groups by supplier — one PO per supplier per run.
   */
  static async checkAndReorder() {
    const lowStockProducts = await Product.find({
      $expr: { $lte: ['$stock', '$lowStockThreshold'] }
    }).lean();

    if (lowStockProducts.length === 0) return [];

    // Get all suppliers and their associated products
    const suppliers = await Supplier.find({ isActive: true }).lean();
    const supplierProductMap = {};

    for (const supplier of suppliers) {
      supplierProductMap[supplier._id.toString()] = supplier;
    }

    // Build supplier → items mapping
    // We match products to suppliers via Supplier.products array
    const allSuppliers = await Supplier.find({ isActive: true, products: { $exists: true, $not: { $size: 0 } } })
      .select('_id products paymentTerms')
      .lean();

    const productToSupplier = {};
    for (const supplier of allSuppliers) {
      for (const productId of (supplier.products || [])) {
        productToSupplier[productId.toString()] = supplier._id.toString();
      }
    }

    const posBySupplier = {};
    const unassigned = [];

    for (const product of lowStockProducts) {
      const supplierId = productToSupplier[product._id.toString()];
      if (!supplierId) { unassigned.push(product.name); continue; }

      if (!posBySupplier[supplierId]) {
        posBySupplier[supplierId] = { supplier: supplierId, items: [] };
      }

      const annualDemand = (product.salesCount || 1) * 12;
      const orderQty = ReorderSystem.calculateEOQ(annualDemand);
      const estimatedCost = product.price * 0.6; // assume 40% retail margin

      posBySupplier[supplierId].items.push({
        product: product._id,
        quantity: orderQty,
        unitPrice: estimatedCost,
        totalPrice: orderQty * estimatedCost,
        receivedQuantity: 0
      });
    }

    const createdPOs = [];
    for (const supplierId in posBySupplier) {
      const poData = posBySupplier[supplierId];
      const totalAmount = poData.items.reduce((s, i) => s + i.totalPrice, 0);

      const poNumber = await OrderCounter.nextOrderNumber('APO'); // Auto-PO prefix

      const po = await PurchaseOrder.create({
        poNumber,
        supplier: supplierId,
        items: poData.items,
        totalAmount,
        status: 'draft',
        expectedDeliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        notes: 'Auto-generated by reorder system'
      });

      createdPOs.push(po);
    }

    if (unassigned.length > 0) {
      console.log(`[ReorderSystem] Products without assigned supplier (skipped): ${unassigned.join(', ')}`);
    }

    return createdPOs;
  }

  /**
   * Demand forecast per product using weighted moving average over weekly sales.
   */
  static async forecastDemand(productId, weeksBack = 8) {
    const Order = require('../models/Order');
    const mongoose = require('mongoose');
    const since = new Date(Date.now() - weeksBack * 7 * 86400000);

    const weeklySales = await Order.aggregate([
      { $match: { isPaid: true, createdAt: { $gte: since } } },
      { $unwind: '$items' },
      { $match: { 'items.product': new mongoose.Types.ObjectId(productId) } },
      {
        $group: {
          _id: { year: { $isoWeekYear: '$createdAt' }, week: { $isoWeek: '$createdAt' } },
          units: { $sum: '$items.quantity' }
        }
      },
      { $sort: { '_id.year': 1, '_id.week': 1 } }
    ]);

    const units = weeklySales.map(w => w.units);
    if (units.length === 0) return { weeklyForecast: 0, monthlyForecast: 0, confidence: 'low' };

    // Weighted moving average — recent weeks get higher weight
    const n = Math.min(units.length, 4);
    const recent = units.slice(-n);
    const weighted = recent.reduce((s, v, i) => s + v * (i + 1), 0);
    const weightSum = (n * (n + 1)) / 2;
    const wma = weighted / weightSum;

    return {
      weeklyForecast: Math.ceil(wma),
      monthlyForecast: Math.ceil(wma * 4.33),
      confidence: units.length >= 4 ? 'medium' : 'low',
      dataPoints: units.length
    };
  }
}

module.exports = ReorderSystem;
